[sprite_sheet.game]
texture_image = "assets/lfs/textures/game.png"
sprites = [
    # Exterior
    { x = 0,   y = 0, width = 32, height = 32 }, # Sprite 0
    # Wall
    { x = 32,  y = 0, width = 32, height = 32 }, # Sprite 1
    # Floor
    { x = 64,  y = 0, width = 32, height = 32 }, # Sprite 2
    # Goal
    { x = 96,  y = 0, width = 32, height = 32 }, # Sprite 3
    # Box
    { x = 128, y = 0, width = 32, height = 32 }, # Sprite 4
    # Player
    { x = 160, y = 0, width = 32, height = 32 }, # Sprite 5
]
