[[entity]]

[entity.components.SpriteRender]
fill = { width = 1000, height = 800, color = [0, 0, 0, 120] }

[entity.components.Transform]
translation = { x = 500.0, y = 400.0 }
depth = 1.0


[[entity]]

[entity.components.Text]
id = "level_complete"
text = "LEVEL COMPLETE"
font_face = { font = "joystix", options.size = 60.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = 480, y = 340 }
